### ISSUE TITLE
vst crashes my DAW

### ISSUE THREAD

**Issue by ghost** [austensatterlee/VOSIMSynth#8]
Hello.

I wanted to try VOSIMSynth but it crashes both of my DAWs (Studio One & Tracktion Waveform) as the title already mentions. I tried both versions, the 32bit as well as 64bit. I did not build it myself but instead downloaded the latest (.dll) releases. Is this project still maintained somehow because I saw that it wasnt updated in almost 3 years if I m not mistaken.

Are there any working releases somewhere?

Regards,
Michael

**Comment by austensatterlee** [comment]
Hey Michael, appreciate you checking out the project. Sorry to hear it's not playing nice with those DAWs. Unfortunately as you noted I haven't really had time to work on this project for quite a while.

While I was developing this I almost exclusively tested with Reaper, as that's the only DAW I own. At the moment I'd recommend trying it with Reaper. You could also try one of the more lightweight DAWs I used for testing, such as [SAVIHost](https://www.hermannseib.com/english/savihost.htm), or [VSTHost](https://www.hermannseib.com/english/vsthost.htm).

I've freed up a bit recently and am hoping to make some improvements on this project. While I can't make any guarantees, I'll try to grab a copy of one of those DAWs and see if I can improve the plugin's compatibility.

In the mean time, if you want to compile it yourself and take a stab at debugging the issues with those DAWs, feel free to contact me and I'll try to help as best I can.

**Comment by austensatterlee** [comment]
Looks like the DLL on the release pages is failing even with Reaper. You can get a more updated build from here: https://ci.appveyor.com/project/austensatterlee/vosimsynth/build/job/j5js996djldt31kv/artifacts. Just confirmed the DLL from that page works with Reaper at least.
